# vim:ft=ansible:
name: dev

windows:
  - main:
      #layout: a5c5,364x99,0,0[364x69,0,0,0,364x29,0,70{120x29,0,70,2,120x29,121,70,3,122x29,242,70,4}]
      layout: d427,374x103,0,0{285x103,0,0,0,88x103,286,0[88x33,286,0,2,88x33,286,34,3,88x35,286,68,4]}

      #we change the directory here because tmuxinator expands the alias and
      #makes a really long path
      panes:
        - vim:
          - cd ~/dev/ && clear
        - lower1:
          - cd ~/dev/ && clear
        - lower2:
          - cd ~/dev/ && clear
        - lower3:
          - cd ~/dev/ && clear

  - cli:
      layout: 7bca,362x97,0,0{291x97,0,0,1,70x97,292,0,11}
      panes:
        - main:
          - cd ~/dev && clear
        - other:
